hivelocity/cluster-api-provider-hivelocity

README.md
/kind documentation    
Fixes links
**TODOs**:
=> :book: fixing links

.golangci.yaml
=> :seedling: remove linter "whitespace".

pkg/services/hivelocity/device/device.go
=> :seedling: rename "server" to "device"

README.md, api/v1alpha1/conditions_const.go, api/v1alpha1/hivelocitymachine_types.go, api/v1alpha1/types.go, api/v1alpha1/webhook_suite_test.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachines.yaml, controllers/hivelocitymachine_controller.go, controllers/hivelocitymachine_controller_test.go, main.go, pkg/hvutils/hvutils.go, pkg/hvutils/hvutils_test.go, pkg/services/hivelocity/client/hvclient.go, pkg/services/hivelocity/client/mock/mock_client.go, pkg/services/hivelocity/device/device.go, pkg/services/hivelocity/device/device_test.go
Claim device by setting the corresponding hv-tags.
=> :seedling: set tags for claiming a HV device.

controllers/hivelocitycluster_controller.go, controllers/hivelocitymachine_controller.go, pkg/scope/cluster.go
/kind cleanup
Removing unused Hivelocity secret from cluster scope
**TODOs**:
=> :seedling: Remove hvsecret from clusterScope

pkg/services/hivelocity/device/device.go, pkg/services/hivelocity/device/device_test.go
/kind cleanup
We update the logic of the associate function to include chooseDevice function. This is necessary because we have otherwise two different devices in the main Reconcile function, one which is associated, and one which is chosen to be. This is confusing and is implemented better in this way when a fully associated device object is created within associate and returned by that function.
**TODOs**:
=> :seedling: Update associate device logic and include chooseDevice

Makefile, controllers/hivelocitycluster_controller.go, controllers/hivelocitymachine_controller_test.go, pkg/scope/cluster.go, pkg/scope/machine.go, pkg/services/hivelocity/client/hvclient.go, pkg/services/hivelocity/client/mock/mock_client.go, pkg/services/hivelocity/client/mock/mock_client_test.go, pkg/services/hivelocity/device/device.go, pkg/services/hivelocity/device/device_test.go, test/helpers/envtest.go
Test reconcile of machinecontroller.go
**TODOs**:
=> :seedling: integration tests of reconcile.

.vscode/settings.json, Makefile, go.mod, go.sum, main.go, pkg/services/hivelocity/device/device.go
/kind feature
We need the new option forceReload.
=> :seedling: new version of hv-client-go

pkg/services/hivelocity/client/hvclient.go, pkg/services/hivelocity/client/mock/mock_client.go, pkg/services/hivelocity/client/mock/mock_client_test.go, pkg/services/hivelocity/device/device.go
=> :seedling: return ErrDeviceNotFound in GetDevice().

api/v1alpha1/hivelocitymachine_types.go, api/v1alpha1/zz_generated.deepcopy.go, pkg/services/hivelocity/client/hvclient.go, pkg/services/hivelocity/client/mock/mock_client.go, pkg/services/hivelocity/client/mock/mock_client_test.go, pkg/services/hivelocity/device/device.go, pkg/services/hivelocity/device/device_test.go, test/hvapi/hvutils.go, test/hvapi/hvutils_test.go, test/hvapi/main.go
/kind cleanup
Removing unused functions from API interface, removing unused types and consts, aligning return value of ListDevices and GetDevices.
**TODOs**:
=> :sparkles: Update hvclient

api/v1alpha1/hivelocitycluster_types.go, api/v1alpha1/hivelocitymachine_types.go, api/v1alpha1/hivelocityremediation_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityremediations.yaml
/kind cleanup
Updating a few things in /api. Kubebuilder commands, comments and unused types.
**TODOs**:
=> :seedling: Update kubebuilder cmds in api

api/v1alpha1/hivelocitymachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachinetemplates.yaml, controllers/hivelocitycluster_controller_test.go, pkg/services/hivelocity/client/mock/mock_client.go, pkg/services/hivelocity/device/device.go
/kind feature
Adding tests for HivelocityCluster controller.
**TODOs**:
=> :sparkles: Add tests for HV cluster controller

pkg/services/hivelocity/client/hvclient.go, pkg/services/hivelocity/device/device.go
/kind cleanup
Update rate limit handling to all cases where HV API is called and use native Golang error handling.
**TODOs**:
=> :seedling: Update rate limit handling everywhere

.github/pull_request_template.md
/kind cleanup
Fixing some typos.
**TODOs**:
=> :seedling: Fix typos in PR template

hack/README.md
/kind cleanup
Fixing some typos
**TODOs**:
=> :seedling: Update hack README"

Makefile, controllers/hivelocitycluster_controller.go, controllers/hivelocitymachine_controller.go, docs/book/src/developer/tilt-setup.md, docs/developers/development.md, go.mod, hack/filter-caphv-controller-manager-logs.py, hack/ssh-first-control-plane.sh, hack/tail-caphv-controller-logs.sh, pkg/services/hivelocity/client/hvclient.go, pkg/services/hivelocity/device/state_machine.go
clean up some code and debug cloud-init.
/kind cleanup           Adds tests, refactors, fixes old bugs.
=> :seedling: clean up and debugging cloud-init.

.github/actions/manager-image/action.yaml, .github/actions/metadata/action.yaml, .github/actions/setup-go/action.yaml, .github/workflows/pr-e2e.yaml, Makefile, README.md, config/default/kustomization.yaml, config/default/manager_pull_policy.yaml, controllers/hivelocitycluster_controller.go, docs/book/src/user/getting-started.md, images/cache/Dockerfile, pkg/services/hivelocity/client/hvclient.go, test/e2e/caphv.go
don't power off, if off. And wait 5s
=> :seedling: don't power off, if off. And wait 5s

.github/workflows/pr-e2e.yaml, pkg/services/hivelocity/client/hvclient.go
/kind bug               Fixes a newly discovered bug.
fix e2e tests in CI
=> :seedling: fix e2e tests in CI

.github/actions/setup-go/action.yaml, .github/workflows/pr-e2e.yaml, pkg/services/hivelocity/client/hvclient.go
Test e2e in CI (GithubAction).
=> :seedling: Run e2e test via Github Action.

README.md, docs/book/src/user/getting-started.md
/kind documentation     Adds documentation.
This PR adds more documentation.
=> :book: Docs

Makefile, hack/ci-e2e-capi.sh
/kind other
Fixes #79 
**TODOs**:
=> 🌱 Add yq to fetch e2e machine tag data from hivelocity-ci-envsubst.yaml file

Makefile, test/e2e/Makefile
remove kubectl target for unexpected error due to go.mod replacement
Fixes #87
**TODOs**:
=> 🌱 Use `go install` to use self contained binary

.github/actions/setup-go/action.yaml, .github/workflows/pr-e2e.yaml, Makefile, hack/ci-e2e-capi.sh, hack/ci-e2e-sshkeys.sh, hack/output-for-watch.sh, test/e2e/Makefile, test/e2e/config/hivelocity-ci.yaml, test/e2e/config/hivelocity.yaml
/kind feature 
Fixes #63 
**TODOs**:
=> ✨ Run e2e jobs in github actions

api/v1alpha1/conditions_const.go, controllers/hivelocitycluster_controller.go, controllers/hivelocitycluster_controller_test.go, controllers/hivelocitymachine_controller.go, pkg/secrets/error.go, pkg/services/hivelocity/device/device.go
/kind feature
Part-of #103 
**TODOs**:
=> ✨ Improve condition in the controllers

api/v1alpha1/conditions_const.go, api/v1alpha1/hivelocitycluster_types.go, api/v1alpha1/hivelocitymachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachines.yaml, controllers/hivelocitycluster_controller.go, pkg/services/hivelocity/device/device.go, pkg/services/hivelocity/device/device_test.go
/kind feature
Part-of #103 
**TODOs**:
=> ✨ Improve condition in the controllers - 2

api/v1alpha1/hivelocitymachine_types.go, api/v1alpha1/hivelocitymachine_types_test.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachines.yaml, docs/book/src/crd/index.md, hack/output-for-watch.sh
Rename DeviceState to PowerState.
=> :seedling: Rename DeviceState to PowerState.

controllers/hivelocitymachine_controller_test.go, docs/book/src/developer/setup.md, docs/book/src/topics/provisioning-machines.md, pkg/services/hivelocity/client/mock/mock_client.go, pkg/services/hivelocity/client/mock/mock_client_test.go, pkg/services/hivelocity/device/device.go, pkg/services/hivelocity/device/device_test.go, pkg/services/hivelocity/hvtag/hvtag.go, pkg/services/hivelocity/hvtag/hvtag_test.go
/kind feature
Fixes #115 
**TODOs**:
=> ✨ Add `caphv-use=allow` tag for device usage

.github/workflows/builder-image.yml
Add workflow for releasing caphv builder image.
=> 🌱 add workflow for  builder image

.github/workflows/builder-image.yml
required for copying build.sh
Fixes #
**TODOs**:
=> 🌱 use right context with while building image

hack/boilerplate/boilerplate.py, hack/boilerplate/boilerplate.py.txt, hack/boilerplate/boilerplate_test.py, hack/boilerplate/testdata/default/fail.py, hack/boilerplate/testdata/default/pass.py, hack/boilerplate/testdata/with_config/fail.py, hack/boilerplate/testdata/with_config/pass.py, hack/filter-caphv-controller-manager-logs.py
=> 🌱 migrate to python3 for boilerplate scripts 

Makefile, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocitymachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityremediations.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hivelocityremediationtemplates.yaml
/kind bug               Fixes a newly discovered bug.
`make generate-manifests` fails on Mac. Maybe the version bump fixes the issues.
Relate: #148
=> :seedling: Upgarde to controller-tools v0.14.0
